CREATE user 'bat'@'%' IDENTIFIED BY 'bat1234';
GRANT ALL PRIVILEGES ON *.* TO 'bat'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

ALTER DATABASE baseball DEFAULT CHARACTER SET utf8;

CREATE TABLE baseball.team (
    team_name VARCHAR(45) PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT="Any baseball";
